[server]
headless = true
port = 8501
enableCORS = true
[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"