[theme]
primaryColor = "#4CAF50"  # A calming green
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F0F2F6"  # Light grey for contrast
textColor = "#333333"  # Dark grey for readability
font = "sans serif"  # Clean and modern font
